---
kind: pipeline
name: default
type: kubernetes


platform:
  os: linux
  arch: amd64


steps:

- name: build_new_image_push_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+egar
    DOCKER_REGISTRY_URL: quay.io
    IMAGE_NAME: quay.io/ukhomeofficedigital/egar-python-3
  when:
    branch:
    - master
    event:
    - push

  commands:
  # Wait for the docker service to be up
  - echo "Checking for docker availability."
  - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
  - echo "echo docker now available."
  - docker login -u="$${DOCKER_USERNAME}" -p="$${DOCKER_PASSWORD}" quay.io
  - docker build -t egar-python-3:$${DRONE_COMMIT} .
  - docker tag egar-python-3:$${DRONE_COMMIT} $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/egar-python-3:latest
  - docker push $${DOCKER_REGISTRY_URL}/ukhomeofficedigital/egar-python-3:latest

  volumes:
    - name: dockersock
      path: /var/run
  settings:
    group: build-stage


- name: Push image to artifactory
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest
  pull: always
  failure: ignore
  environment:
    DOCKER_ARTIFACT_PASSWORD:
      from_secret: DOCKER_ARTIFACT_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_ARTIFACT_USERNAME
    DOCKER_ARTIFACT_REGISTRY_URL:
      from_secret: DOCKER_ARTIFACT_REGISTRY_URL
  commands:
  # Wait for the docker service to be up
  - echo "Checking for docker availability."
  - n=0; while [ "$n" -lt 60 ] && ! docker stats --no-stream >/dev/null 2>&1; do n=$(( n + 1 )); sleep 1; done
  - echo "echo docker now available."
  - docker build -t egar-python-3:$${DRONE_COMMIT} .
  - docker tag egar-python-3:$${DRONE_COMMIT} docker.digital.homeoffice.gov.uk/egar/egar-python-3:$${DRONE_COMMIT}
  # - docker login -u="egar-sit" -p=$${DOCKER_ARTIFACT_PASSWORD} docker.digital.homeoffice.gov.uk
  - echo $${DOCKER_ARTIFACT_PASSWORD} | docker login -u="egar-sit" --password-stdin docker.digital.homeoffice.gov.uk
  - docker push docker.digital.homeoffice.gov.uk/egar/egar-python-3:$${DRONE_COMMIT}
  when:
    branch:
    - master
    - feature/*
    event:
    - push

- name: scan-newly-built-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  failure: ignore
  environment:
    IMAGE_NAME: docker.digital.homeoffice.gov.uk/egar/egar-python-3:$${DRONE_COMMIT}
    TOLERATE: high
  when:
    event:
    - push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server

volumes:
  - name: dockersock
    temp: {}
